#include <iostream>
#include <vector>
#include <map>
#include <stack>
#include <sstream>
#include <set>
#include "common/polygon.hpp"
#include "common/convex.hpp"
#include "common/matrix3x3.hpp"
#include "common/problem.hpp"
